"""
Import WoRMS data into PostgreSQL database.
Reads data/worms/species/_all_species.json and inserts into shrimp_species table.
"""

import json
import os
import sys
import uuid

DATA_FILE = os.path.join(os.path.dirname(__file__), "worms", "species", "_all_species.json")
OUTPUT_FILE = "/tmp/worms_import.sql"

def load_worms():
    with open(DATA_FILE, encoding="utf-8") as f:
        return json.load(f)

def scientific_to_cn(name: str) -> str:
    """Generate a reasonable Chinese name from scientific name patterns"""
    name_map = {
        "Penaeus vannamei": "南美白对虾",
        "Penaeus monodon": "斑节对虾",
        "Penaeus chinensis": "中国对虾",
        "Penaeus japonicus": "日本对虾",
        "Penaeus merguiensis": "墨吉对虾",
        "Penaeus indicus": "印度对虾",
        "Penaeus subtilis": "巴西对虾",
        "Penaeus setiferus": "美洲白对虾",
        "Penaeus aztecus": "褐色对虾",
        "Penaeus duorarum": "粉红对虾",
        "Metapenaeus ensis": "短沟对虾",
        "Metapenaeus bennettae": "澳洲草虾",
        "Metapenaeus mastersii": "棕色虎虾",
        "Trachysalambria curvirostris": "竹节虾",
        "Macrobrachium rosenbergii": "罗氏沼虾",
        "Macrobrachium nipponense": "日本沼虾",
        "Macrobrachium carcinus": "美洲大沼虾",
        "Neocaridina denticulata": "樱桃虾",
        "Crangon crangon": "欧洲褐虾",
        "Pandalus borealis": "北极甜虾",
        "Pandalus montagui": "粉红虾",
        "Pandalus jordani": "太平洋粉红虾",
        "Hippolyte inermis": "海草虾",
        "Lysmata seticaudata": "清洁虾",
        "Lysmata debelius": "火焰清洁虾",
        "Lysmata amboinensis": "白纹清洁虾",
        "Pasiphaea japonica": "日本玻璃虾",
        "Pasiphaea sivado": "普通玻璃虾",
        "Acetes japonicus": "樱花虾",
        "Acetes intermedius": "中型樱虾",
        "Plesiopenaeus edwardsianus": "深红虾",
        "Benthesicymus tanneri": "深海底虾",
        "Gennadas valens": "深海总科虾",
        "Alpheus heterochaelis": "枪虾",
        "Alpheus bellimanus": "壮美枪虾",
        "Stenopus hispidus": "毛刷清洁虾",
        "Heterocarpus relictus": "岩礁虾",
        "Processa edulis": "荷兰虾",
    }
    return name_map.get(name, "")

def scientific_to_en(name: str) -> str:
    """Generate English name from scientific name patterns"""
    en_map = {
        "Penaeus vannamei": "Whiteleg Shrimp",
        "Penaeus monodon": "Giant Tiger Prawn",
        "Penaeus chinensis": "Chinese Shrimp",
        "Penaeus japonicus": "Japanese Shrimp",
        "Penaeus merguiensis": "Banana Shrimp",
        "Penaeus indicus": "Indian Shrimp",
        "Penaeus subtilis": "Brown Shrimp",
        "Penaeus setiferus": "Pacific White Shrimp",
        "Penaeus aztecus": "Brown Shrimp",
        "Penaeus duorarum": "Pink Shrimp",
        "Metapenaeus ensis": "Green Tail Shrimp",
        "Metapenaeus bennettae": "Greasyback Shrimp",
        "Metapenaeus mastersii": "Brown Tiger Prawn",
        "Trachysalambria curvirostris": "Ocean Shrimp",
        "Macrobrachium rosenbergii": "Giant Freshwater Prawn",
        "Macrobrachium nipponense": "Japanese Freshwater Shrimp",
        "Macrobrachium carcinus": "American Giant Freshwater Shrimp",
        "Neocaridina denticulata": "Cherry Shrimp",
        "Crangon crangon": "European Brown Shrimp",
        "Pandalus borealis": "Northern Prawn",
        "Pandalus montagui": "Pink Shrimp",
        "Pandalus jordani": "Ocean Shrimp",
        "Hippolyte inermis": "Sea Grass Shrimp",
        "Lysmata seticaudata": "Cleaner Shrimp",
        "Lysmata debelius": "Fire Cleaner Shrimp",
        "Lysmata amboinensis": "White-spot Cleaner Shrimp",
        "Pasiphaea japonica": "Japanese Glass Shrimp",
        "Pasiphaea sivado": "Norway Shrimp",
        "Acetes japonicus": "Akiami Paste Shrimp",
        "Acetes intermedius": "Mid-sized Paste Shrimp",
        "Plesiopenaeus edwardsianus": "Scarlet Shrimp",
        "Benthesicymus tanneri": "Deep Sea Shrimp",
        "Gennadas valens": "Deep Sea Benthesicymid Shrimp",
        "Alpheus heterochaelis": "Snapping Shrimp",
        "Alpheus bellimanus": "Major Pistol Shrimp",
        "Stenopus hispidus": "Banded Coral Shrimp",
        "Heterocarpus relictus": "Reef Shrimp",
        "Processa edulis": "Dutch Shrimp",
    }
    return en_map.get(name, "")

def generate_insert_sql(species_list):
    """Generate SQL INSERT statements"""
    lines = []
    lines.append("-- WoRMS species data import")
    lines.append("-- Generated by import_worms.py")
    lines.append("")

    for sp in species_list:
        sci_name = sp.get("scientific_name", "")
        cn_name = scientific_to_cn(sci_name) or sp.get("cn_name", "")
        en_name = scientific_to_en(sci_name) or sp.get("en_name", "")
        family = sp.get("family", "")
        genus = sp.get("genus", "")
        is_marine = sp.get("is_marine", 1)
        habitat = "coastal" if is_marine else "freshwater"

        # Determine edible status based on known commercial species
        commercial_species = [
            "Penaeus vannamei", "Penaeus monodon", "Penaeus chinensis",
            "Penaeus japonicus", "Penaeus merguiensis", "Penaeus indicus",
            "Penaeus setiferus", "Penaeus aztecus", "Penaeus duorarum",
            "Metapenaeus ensis", "Metapenaeus bennettae", "Trachysalambria curvirostris",
            "Macrobrachium rosenbergii", "Crangon crangon", "Pandalus borealis",
            "Acetes japonicus",
        ]
        is_edible = "TRUE" if sci_name in commercial_species else "FALSE"

        fishing_type = "both" if sci_name in commercial_species else "wild"

        # Determine temperature zone based on known distribution
        tropical = ["Penaeus vannamei", "Penaeus monodon", "Penaeus merguiensis",
                    "Penaeus indicus", "Metapenaeus ensis", "Macrobrachium rosenbergii",
                    "Acetes japonicus", "Alpheus heterochaelis"]
        cold_water = ["Pandalus borealis", "Crangon crangon", "Plesiopenaeus edwardsianus"]
        temp_zone = "tropical" if sci_name in tropical else ("cold" if sci_name in cold_water else "temperate")

        # IUCN status (most shrimp are LC - data deficient for many)
        iucn_map = {
            "Penaeus vannalei": "LC", "Penaeus monodon": "LC",
            "Macrobrachium rosenbergii": "LC", "Pandalus borealis": "LC",
        }
        iucn = iucn_map.get(sci_name, "DD")

        sql = (
            f"INSERT INTO shrimp_species "
            f"(id, cn_name, en_name, scientific_name, family, genus, habitat, "
            f"temperature_zone, is_edible, fishing_type, iucn_status, created_at) "
            f"VALUES ("
            f"'{uuid.uuid4()}', "
            f"'{cn_name.replace("'", "''")}', "
            f"'{en_name.replace("'", "''")}', "
            f"'{sci_name.replace("'", "''")}', "
            f"'{family.replace("'", "''")}', "
            f"'{genus.replace("'", "''")}', "
            f"'{habitat}', "
            f"'{temp_zone}', "
            f"{is_edible}, "
            f"'{fishing_type}', "
            f"'{iucn}', "
            f"NOW()"
            f");"
        )
        lines.append(sql)

    return "\n".join(lines)

if __name__ == "__main__":
    print("Loading WoRMS data...")
    species = load_worms()
    print(f"Found {len(species)} species")

    sql = generate_insert_sql(species)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"SQL written to {OUTPUT_FILE}")
    print(f"Total INSERT statements: {sql.count('INSERT INTO')}")
